title: van42 - A campervan travel log

theme: jekyll-theme-minimal
#theme: jekyll-theme-architect
#remote_theme: pages-themes/minimal

# fixes this: https://talk.jekyllrb.com/t/error-your-site-could-not-be-built-no-repo-name-found/5688
repository: van4two/van4two.github.io

# https://jekyllrb.com/docs/plugins/installation/
plugins:
#- jekyll-remote-theme # github remote themes
- jekyll-toc
- jekyll-archives
- jekyll-leaflet
- jekyll-target-blank # https://github.com/keithmifsud/jekyll-target-blank
- jekyll-google-photos
#- jekyll-maps

exclude:
- '*.sh'
- '.devcontainer'
- '*.code-workspace'
- 'Gemfile*'
- 'wp-jekyll'

#permalinks: pretty

jekyll-archives:
  enabled: [year, month, tags]
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
    
