name: Testing the GitHub Pages publication

on:
  push:
    branches: main
    
  workflow_dispatch:
  
jobs:
  jekyll:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        # Use GitHub Actions' cache to shorten build times and decrease load on servers
    
